import 'package:amplify_core/amplify_core.dart';
import 'package:flutter/cupertino.dart';
import 'package:get/get.dart';

class AddGreenHouseController extends GetxController {
  final formKey = GlobalKey<FormState>();

  late TextEditingController nameController;
  late TextEditingController microcontrollerIdController;
  late TextEditingController cropNameController;
  late TextEditingController cropTimePeriodController;

  RxBool isActive = true.obs; // For greenhouse status

  @override
  void onInit() {
    nameController = TextEditingController();
    microcontrollerIdController = TextEditingController();
    cropNameController = TextEditingController();
    cropTimePeriodController = TextEditingController();

    super.onInit();
  }

  @override
  void onClose() {
    nameController.dispose();
    microcontrollerIdController.dispose();
    cropNameController.dispose();
    cropTimePeriodController.dispose();
    super.onClose();
  }

  Future<void> saveGreenhouse() async {
    if (formKey.currentState!.validate()) {
      // try {
      //   final newGreenhouse = Greenhouse(
      //     // greenhouseId is auto-generated by DataStore
      //     microcontrollerId: microcontrollerIdController.text, // Added
      //     name: nameController.text,
      //     cropName: cropNameController.text, // Added
      //     cropTimePeriod: int.parse(
      //         cropTimePeriodController.text), // Added, assuming integer days
      //     isActive: isActive.value,
      //   );
      //
      //   await Amplify.DataStore.save(newGreenhouse);
      //   Get.back();
      //   Get.snackbar('Success', 'Greenhouse added!',
      //       snackPosition: SnackPosition.BOTTOM);
      // } catch (e) {
      //   print('Error saving greenhouse: $e');
      //   Get.snackbar('Error', 'Failed to add greenhouse. Please try again.',
      //       snackPosition: SnackPosition.BOTTOM);
      // }
    }
  }
}
